### ISSUE TITLE
how to make a view fill the space between 2 views to which it is constrained using VFL/EVFL

### ISSUE THREAD

**Issue by gbenroscience** [lume/autolayout#1]
Thanks a whole lot for this library.

I am constraining a view between 2 others. Say, view **`V`** is between views **`A`** and **`B`**. Let's say **`A`** is to the left and **`B`** is to the right.(Or **`A`** is to the top and **`B`** is to the bottom)
I want view **`V`** to fill the space between **`A`** and **`B`** totally. I am using **EVFL**.
How can I accomplish this, please.

Thanks.

**Comment by trusktr** [comment]
Hello! Sorry for the very late response. I hope you figured it out:

```js
H:|-[A(200)]-[V]-[B(100)]-|
```

^ In this example, `A` is on the left edge and has width 200, `B` is on the right edge and has width 100, and `V` is in the middle and takes up the remaining space.

Here is the full horizontal demo (paste it into [the playground](https://rawgit.com/IjzerenHein/visualformat-editor/master/dist/index.html)):

```js
H:|-[A(200)]-[V]-[B(100)]|
V:|-[A]-|
V:|-[V]-|
V:|-[B]-|
```

Here is the full horizontal demo (just swap `H:` and `V:`):

```js
V:|-[A(200)]-[V]-[B(100)]|
H:|-[A]-|
H:|-[V]-|
H:|-[B]-|
```
